name: hourly-push-to-eink

on:


  # 手动触发（在 GitHub UI 会出现 Run workflow 按钮）
  workflow_dispatch:

  schedule:
    - cron: "0,30 8-22 * * *"   # 每天 8:00 到 20:30，每半小时运行一次


jobs:
  push:
    runs-on: ubuntu-latest
    env:
      API_URL: https://dot.mindreset.tech/api/open/text
      API_KEY: ${{ secrets.DOT_API_KEY }}
      DEVICE_ID: ${{ secrets.DEVICE_ID }}
      EXCEL_FILE: data.xlsx

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install pandas openpyxl requests pillow

      - name: Run push script
        run: |
          python push_random_action.py || true

        
